### PR TITLE
[Feature] support objects

### PR DESCRIPTION
**Pull request by ghost**
Adds support on exporting and importing objects as described in #1 

Export:
```php
# src/foo.php:
<?php 

namespace MyNamespace;

class Foo {
    public function __construct($bar) {
        echo $bar . 'world';
    }
}

export(Foo::class);
```

Import:
```php
# src/index.php:
<?php
$foo = import('foo'); // equals MyNamespace\Foo

new $foo('helllo'); // prints 'hello world'
```

### CODE REVIEW

**Review by nunomaduro — CHANGES_REQUESTED** [review]
Seems that tests are failing, please run `composer test` locally.

Can you also add some tests?

**Comment by ghost** [comment]
Working on it :)

**Comment by ghost** [comment]
I've added tests and fixed almost all of the errors from phpstan, the only problem is that there are 2 phpstan errors I can't fix.
@nunomaduro  Can you please take a look?

**Review by ghost — COMMENTED** [review]
👍

**Review by ghost — COMMENTED** [review]
👍

**Pull request closed without merging**
