### PR TITLE
My 2 cents

### PR DESCRIPTION
**Pull request by lyrixx**

### CODE REVIEW

**Comment by lyrixx** [comment]
I have one question though: what problem does this package solve?

**Comment by lyrixx** [comment]
ping @nunomaduro

**Comment by nunomaduro** [comment]
@lyrixx Not sure yet. I am just having fun.

**Comment by nunomaduro** [comment]
Seems that tests are not passing, can you double check?

**Comment by lyrixx** [comment]
Tests do not pass on default branch either.

> Seems that tests are not passing, can you double check?

Since I don't use this package, I can't. Sorry.

I'm closing this PR. But feel free to cherry-pick my commit

**Pull request closed without merging**
